### ISSUE TITLE
to build on Mac

### ISSUE THREAD

**Issue by rakanbakir** [SmallPP420/PS4-Firmware-Downloader#1]
To build in Mac (moneterery)

dotnet publish "./PS4 Firmware Downloader.csproj" --output "build/" -r osx-x64 -p:UseAppHost=True --self-contained true

**Comment by halal-beef** [comment]
Hello, does the main app actually run on Mac OS?

**Comment by halal-beef** [comment]
And does it download etc etc

**Comment by rakanbakir** [comment]
Dear,

Yes the main app run on Mac, if you like I can provide it to you, for the second question, sorry I did not understand it, can you explain it more.

**Comment by halal-beef** [comment]
Does the app download the PS4 update successfully?

**Comment by rakanbakir** [comment]
Yes it does

**Comment by halal-beef** [comment]
Okay, I'll add the command in thank you
